=== 1310f/nutch-in-java/src/main/resources/index-writers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License (MIT)

Copyright (c) 2019 Yegor Bugayenko

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://lucene.apache.org/nutch" targetNamespace="http://lucene.apache.org/nutch" elementFormDefault="qualified">
  <xs:element name="writers">
    <xs:annotation>
      <xs:documentation>
        Root tag of index-writers.xml document. It's a wrapper for the all index writers.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="writer" type="writerType" maxOccurs="unbounded" minOccurs="1">
          <xs:annotation>
            <xs:documentation>
              Contains all the configuration of a particular index writer.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="writerType">
    <xs:sequence>
      <xs:element type="parametersType" name="parameters" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            This tag contains all the parameters that will be passed to the index writer implementation.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="mappingType" name="mapping" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            It's a wrapper for the allowed actions over a document before it's indexed.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required">
      <xs:annotation>
        <xs:documentation>
          Writer's ID.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:string" name="class" use="required">
      <xs:annotation>
        <xs:documentation>
          The class of the index writer implementation which will be used.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="parametersType">
    <xs:sequence>
      <xs:element type="parameterType" name="param" maxOccurs="unbounded" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            One single parameter that will be pass to the index writer implementation.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parameterType">
    <xs:attribute type="xs:string" name="name" use="required">
      <xs:annotation>
        <xs:documentation>
          Parameter's name. It is used to identify the parameter.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:string" name="value" use="required">
      <xs:annotation>
        <xs:documentation>
          Parameter's value.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="mappingType">
    <xs:sequence>
      <xs:element type="fieldsType" name="copy" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Action of copy fields. Multiple comma-separated targets can be specified.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="fieldsType" name="rename" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Action of rename fields.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="remove" maxOccurs="1" minOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Action of remove fields.
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" maxOccurs="unbounded" minOccurs="0">
              <xs:annotation>
                <xs:documentation>
                  One single field that will be mapped.
                </xs:documentation>
              </xs:annotation>
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="source" use="required">
                      <xs:annotation>
                        <xs:documentation>
                          Field's name before it's mapped.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fieldsType">
    <xs:sequence>
      <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0">
        <xs:annotation>
          <xs:documentation>
            One single field that will be mapped.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fieldType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="source" use="required">
          <xs:annotation>
            <xs:documentation>
              Field's name before it's mapped.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" name="dest" use="required">
          <xs:annotation>
            <xs:documentation>
              Field's name after the action is applied.
            </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== 1310f/nutch-in-java/src/main/resources/index-writers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License (MIT)

Copyright (c) 2019 Yegor Bugayenko

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<writers xmlns="http://lucene.apache.org/nutch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lucene.apache.org/nutch index-writers.xsd">
  <writer id="indexer_solr_1" class="org.apache.nutch.indexwriter.solr.SolrIndexWriter">
    <parameters>
      <param name="type" value="http"/>
      <param name="url" value="http://localhost:8983/solr/nutch"/>
      <param name="collection" value=""/>
      <param name="weight.field" value=""/>
      <param name="commitSize" value="1000"/>
      <param name="auth" value="false"/>
      <param name="username" value="username"/>
      <param name="password" value="password"/>
    </parameters>
    <mapping>
      <copy>
        <!-- <field source="content" dest="search"/> -->
        <!-- <field source="title" dest="title,search"/> -->
      </copy>
      <rename>
        <field source="metatag.description" dest="description"/>
        <field source="metatag.keywords" dest="keywords"/>
      </rename>
      <remove>
        <field source="segment"/>
      </remove>
    </mapping>
  </writer>
  <writer id="indexer_rabbit_1" class="org.apache.nutch.indexwriter.rabbit.RabbitIndexWriter">
    <parameters>
      <param name="server.uri" value="amqp://guest:guest@localhost:5672/"/>
      <param name="binding" value="false"/>
      <param name="binding.arguments" value=""/>
      <param name="exchange.name" value=""/>
      <param name="exchange.options" value="type=direct,durable=true"/>
      <param name="queue.name" value="nutch.queue"/>
      <param name="queue.options" value="durable=true,exclusive=false,auto-delete=false"/>
      <param name="routingkey" value=""/>
      <param name="commit.mode" value="multiple"/>
      <param name="commit.size" value="250"/>
      <param name="headers.static" value=""/>
      <param name="headers.dynamic" value=""/>
    </parameters>
    <mapping>
      <copy>
        <field source="title" dest="title,search"/>
      </copy>
      <rename>
        <field source="metatag.description" dest="description"/>
        <field source="metatag.keywords" dest="keywords"/>
      </rename>
      <remove>
        <field source="content"/>
        <field source="segment"/>
        <field source="boost"/>
      </remove>
    </mapping>
  </writer>
  <writer id="indexer_dummy_1" class="org.apache.nutch.indexwriter.dummy.DummyIndexWriter">
    <parameters>
      <param name="delete" value="false"/>
      <param name="path" value="./dummy-index.txt"/>
    </parameters>
    <mapping>
      <copy/>
      <rename/>
      <remove/>
    </mapping>
  </writer>
  <writer id="indexer_csv_1" class="org.apache.nutch.indexwriter.csv.CSVIndexWriter">
    <parameters>
      <param name="fields" value="id,title,content"/>
      <param name="charset" value="UTF-8"/>
      <param name="separator" value=","/>
      <param name="valuesep" value="|"/>
      <param name="quotechar" value="&quot;"/>
      <param name="escapechar" value="&quot;"/>
      <param name="maxfieldlength" value="4096"/>
      <param name="maxfieldvalues" value="12"/>
      <param name="header" value="true"/>
      <param name="outpath" value="csvindexwriter"/>
    </parameters>
    <mapping>
      <copy/>
      <rename/>
      <remove/>
    </mapping>
  </writer>
  <writer id="indexer_elastic_1" class="org.apache.nutch.indexwriter.elastic.ElasticIndexWriter">
    <parameters>
      <param name="host" value=""/>
      <param name="port" value="9300"/>
      <param name="cluster" value=""/>
      <param name="index" value="nutch"/>
      <param name="max.bulk.docs" value="250"/>
      <param name="max.bulk.size" value="2500500"/>
      <param name="exponential.backoff.millis" value="100"/>
      <param name="exponential.backoff.retries" value="10"/>
      <param name="bulk.close.timeout" value="600"/>
    </parameters>
    <mapping>
      <copy>
        <field source="title" dest="title,search"/>
      </copy>
      <rename/>
      <remove/>
    </mapping>
  </writer>
  <writer id="indexer_elastic_rest_1" class="org.apache.nutch.indexwriter.elasticrest.ElasticRestIndexWriter">
    <parameters>
      <param name="host" value=""/>
      <param name="port" value="9200"/>
      <param name="index" value="nutch"/>
      <param name="max.bulk.docs" value="250"/>
      <param name="max.bulk.size" value="2500500"/>
      <param name="user" value="user"/>
      <param name="password" value="password"/>
      <param name="type" value="doc"/>
      <param name="https" value="false"/>
      <param name="trustallhostnames" value="false"/>
      <param name="languages" value=""/>
      <param name="separator" value="_"/>
      <param name="sink" value="others"/>
    </parameters>
    <mapping>
      <copy>
        <field source="title" dest="search"/>
      </copy>
      <rename/>
      <remove/>
    </mapping>
  </writer>
  <writer id="indexer_cloud_search_1" class="org.apache.nutch.indexwriter.cloudsearch.CloudSearchIndexWriter">
    <parameters>
      <param name="endpoint" value=""/>
      <param name="region" value=""/>
      <param name="batch.dump" value="false"/>
      <param name="batch.maxSize" value="-1"/>
    </parameters>
    <mapping>
      <copy/>
      <rename/>
      <remove/>
    </mapping>
  </writer>
</writers>
